name = "Survie sur l'eau"
author = "Mathiol"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3945f7b0b9f6cf4bcec175926b3bf5483e26b9b820aa777c35fc024aa0290a59"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
