name = "Survie sur l'eau"
author = "Mathiol"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4933aac32467fd401a34a0a0c631cb267dc581594bf9bd5681a680f2cdebf4e9"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
